project:
  type: website
  output-dir: _slides
  render: [index.qmd]
  pre-render: "R/_pre-render-revealjs.R"
  post-render: "R/_post-render-revealjs.R"

title: "Associations Between Sleep and Labor Duration"
author: "Alícia Sales"
institute: "University of São Paulo"
date: today
date-format: "DD/MM/YYYY"

website:
  favicon: images/favicon.png
  site-url: https://aliciarvilefortsales.github.io/mastersthesis/
  repo-url: https://github.com/aliciarvilefortsales/mastersthesis/
  issue-url: https://github.com/aliciarvilefortsales/mastersthesis/issues/
  repo-branch: main

format:
  revealjs:
    locale: en
    lang: en
    code-link: true
    code-fold: true
    link-external-newwindow: true
    tbl-cap-location: top
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    preview-links: false
    controls: true
    controls-layout: bottom-right
    chalkboard: true
    auto-stretch: true
    fig-align: center
    theme: [default, brand, scss/slides.scss]
    pdf-max-pages-per-slide: 1
    template-partials:
      - html/title-slide.html
    menu:
      titleSelector: [h1 h2]
      useTextContentForMissingTitles: false
      hideMissingTitles: false
    include-in-header: "html/include-in-header.html"
