brand: false

project:
  type: book
  output-dir: _print
  pre-render: "R/_pre-render-pdf.R"
  post-render: "R/_post-render-pdf.R"

filters:
  - latex-environment
commands:
  - legend
  - brandprimary
  - brandblack

execute:
  echo: false

book:
  author: "Alícia Rafaelly Vilefort Sales"
  date: today
  date-format: "YYYY"
  chapters:
    - index.qmd
    - qmd/chapter-2.qmd
    - qmd/chapter-3.qmd
    - qmd/chapter-4.qmd
    - qmd/glossary.qmd
  appendices:
    - qmd/appendix-1.qmd

format:
  abnt-pdf:
    zotero: true
    toc-depth: 2
    biblio-style: apa
    biblio-title: REFERENCES
    biblio-footnote: >
      In accordance with the American Psychological Association
      (APA) Style, 7th edition.
    bibhang: 0.5cm
    bibparsep: 1ex
    body-color: "63483E" # Brand Black
    mainfont: Open Sans
    sansfont: Open Sans
    monofont: Source Code Pro
    colorlinks: true
    linkcolor: brand-primary
    filecolor: brand-primary
    citecolor: brand-primary
    urlcolor: brand-primary
    location: "São Paulo"
    supervisor: "Christiane Borges do Nascimento Chofakian"
    academic-title: "Master"
    academic-degree: "Master of Science"
    type-of-work: "Thesis"
    area-of-concentration: "Healthcare"
    university: "University of São Paulo"
    school: "School of Nursing"
    program: "Graduate Program in Nursing"
    version-note: "Preliminary version"
    include-in-header: tex/include-in-header.tex
    include-before-body: tex/include-before-body.tex
    include-after-body: tex/include-after-body.tex
