project:
  type: book
  output-dir: _web
  pre-render: "R/_pre-render-html.R"
  post-render: "R/_post-render-html.R"

book:
  author: "AlÃ­cia Sales"
  date: today
  date-format: "YYYY-MM-DD"
  reader-mode: true
  repo-actions: [edit, issue]
  sidebar:
    tools:
      - icon: file-earmark-pdf-fill
        href: ../print/index.pdf
  chapters:
    - index.qmd
    - part: "Preliminary Sections"
      chapters:
        - qmd/errata.qmd
        - qmd/inscription.qmd
        - qmd/acknowledgments.qmd
        - qmd/epigraph.qmd
        - qmd/vernacular-abstract.qmd
        - qmd/foreign-abstract.qmd
        - qmd/list-of-abbreviations.qmd
        - qmd/list-of-symbols.qmd
    - part: "Chapters"
      chapters:
        - qmd/chapter-1.qmd
        - qmd/chapter-2.qmd
        - qmd/chapter-3.qmd
        - qmd/chapter-4.qmd
    - qmd/references.qmd
    - qmd/glossary.qmd
  appendices:
    - qmd/appendix-1.qmd
  comments:
    hypothesis:
      theme: clean
      openSidebar: false

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    dev: "ragg_png" # Set `AGG` as the backend of your graphic device.
    dev.args:
      bg: "transparent"

format:
  html:
    date-format: "YYYY-MM-DD"
    open-graph: true
    locale: en
    language: en
    code-fold: true
    code-link: true
    code-tools: false
    df-print: paged
    cap-location: top
    fig-align: center
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    repo-actions: true
    link-external-icon: false
    link-external-newwindow: false
    theme: [cosmo, brand, scss/web.scss]
    include-in-header: "html/include-in-header.html"
